### ISSUE TITLE
Geonames: Still some issues with matching strings to locations, wrong links/URIs - pre-processing necessary

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#19]
E.g "Paris" gets linked to the location "Paris Creek" instead of "Paris" (http://data.silknow.org/production/6b276c1a-f0e0-314b-98ac-cdede8d59a6a)

**Comment by tschleider** [comment]
@pasqLisena  committed some improvements about this ( especially for MET ) already, but there is some more work to do. For example we should normalise "French" into "France", but sometimes we have extra information like "Probably" or "found in" or "made in", that we should not remove. We thought about a way to store that extra information somewhere else as a comment before removing it from the string.

**Comment by rtroncy** [comment]
This is interesting. Can you provide example links of those records?

The "found in" and "made in" may be represented using different properties in the model since it does not convey the same semantics. @mpuren what do you think?

The "probably" is a qualifier, so this is something else that could indeed be represented in a textual note.

**Comment by tschleider** [comment]
MET has more information that we now collect thanks to a crawler update: another field with more complete information about the location (e.g.) Europe, France, Sèvres for 00.1.18.json instead of only "French". This should be taken into account.

**Comment by mpuren** [comment]
@tschleider : could you give me an example with "found in" ? Because it is very very rare to "find" a textile. Textile pieces are very difficult to preserve in general, so they are very rarely found. More "traditional" archeological artifacts can be found in a grave (yes, sometimes archeologists find egyptian fabric by example), in the soil, in ancient houses... For our period of time, it would be very surprising (and also very interesting for historians). So we will map it for sure. Maybe with :
S19_Encounter Event O19 has found object E22_Man-Made Object
S19_Encounter Event O21 has found at E53_Place

**Comment by tschleider** [comment]
@mpuren 
sorry for my very late answer! I went over it again and could not find any examples for "found in", so either i mixed it up with "founded", as some locations strings included that word. Or I just assumed it could be possible in cases where we do not have extra information, but of course I am not an expert.

It was in all cases a consideration that in many cases the location is not 100% clear / defined. I have not updated our implementation yet to include the "probably" part, but I will still work on it.

**Comment by rtroncy** [comment]
I'm closing this issue. Follow-up work should be done in issue #41.
