### ISSUE TITLE
Subject depictions: "E36_Visual Item" should be used instead of "P62_depicts"

### ISSUE THREAD

**Issue by tschleider** [silknow/converter#29]
The making of subject depictions changed at some point in the mappings and is not reflected yet in the converter/the knowledge graph. I do not consider it a bug as all the information is available in the KG, but according to the mapping it's not located perfectly.

**Comment by rtroncy** [comment]
The [mapping file for IMATEX](https://docs.google.com/document/d/1_DMd0aF4aweBmBKBMV11aUYzttqGT2ecTFAAJ0vNT6E/edit#heading=h.bhjtsck21tv8) shows indeed that the new path should be `E22_Man-Made_Object P65_shows_visual_item E36_Visual Item` and a `E36_Visual_Item has a P3_has_note E62_String`. If we have no other information to attach to the Visual Item, then it is better to simply use the `P62_depicts` property. I'm asking clarifications from @mpuren 

The following query shows that we should be able to much better interlink the subject depictions ([results](https://data.silknow.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+%3Fo+%3Flabel+%3Fprod+%3Fdepiction+%3Fts+%3Floc%0D%0AWHERE+%7B%0D%0A++GRAPH+%3Fg+%7B%0D%0A+++++%3Fo+a+ecrm%3AE22_Man-Made_Object+.%0D%0A++%7D%0D%0A++%3Fo+rdfs%3Alabel+%3Flabel+.%0D%0A++%3Fprod+ecrm%3AP108_has_produced+%3Fo+.%0D%0A++%3Fo+ecrm%3AP62_depicts+%3Fdepiction%0D%0A++OPTIONAL+%7B+%3Fprod+ecrm%3AP4_has_time_span+%3Fts+.+%7D%0D%0A++OPTIONAL+%7B+%3Fprod+ecrm%3AP8_took_place_on_or_within+%3Floc+.+%7D%0D%0A%7D%0D%0ALIMIT+100%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)), e.g. Motivos florales; Motivos vegetales; Motivos geométricos since the semi column seems to be an easy separator to use:

```
SELECT DISTINCT ?o ?label ?prod ?depiction ?ts ?loc
WHERE {
  GRAPH ?g {
     ?o a ecrm:E22_Man-Made_Object .
  }
  ?o rdfs:label ?label .
  ?prod ecrm:P108_has_produced ?o .
  ?o ecrm:P62_depicts ?depiction
  OPTIONAL { ?prod ecrm:P4_has_time_span ?ts . }
  OPTIONAL { ?prod ecrm:P8_took_place_on_or_within ?loc . }
}
LIMIT 100

```

**Comment by rtroncy** [comment]
@mpuren checked and the `P62_depicts` property should NEVER be used in the current mappings. We should always use instead the path:
 `E22_Man-Made_Object P65_shows_visual_item E36_Visual Item `
 `E36_Visual_Item has a P3_has_note E62_String`

@tschleider Can you make sure it is now consistent in the KG to facilitate the queries?

**Comment by tschleider** [comment]
Finally implemented it, pushed to production, example: https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fvisual_item%2F33b242a4-ba01-33c9-b598-472e2235cb34&sid=581

**Comment by rtroncy** [comment]
What is this `/visual_item` in the URI? This is not described in the URI pattern document and not dereferencable yet!

Why not re-using the simple `/image` pattern? What is the relationship between a E36 and a E38?

**Comment by tschleider** [comment]
I gave it a URI that is easily recognisable in the code, we have some mechanisms that can still post-process it before it gets written, therefore it's no poblem.

I can use /image, but we use this for the image files (class) not for categories or descriptions. In an ideal case the motif / subject depiction / visual item is also visible on the image, of course, otherwise they are only connected through the intermediate E22. 

The problem about creating a direct relationship between E36 and E38 might be that if the subject is visible at all (which we also don't know for all cases in advance without checking), we don't know if it's visible on all image files or just specific ones.

**Comment by rtroncy** [comment]
What I meant is that a `ecrm:E38_Image` is a `rdfs:subClassOf` a `ecrm:E36_Visual_Item`. I understand that a Visual Item is more general but the scope note clearly indicates that this class "comprises the intellectual or conceptual aspects of recognisable marks and images".

I think you can overload the /image pattern for identifying Visual Items. There is value in factorizing a bit the number of top level elements you're putting in the URI pattern as this has a maintenance cost (providing dereferencing rules, etc.)

**Comment by tschleider** [comment]
Ok, got it. So I use /image/ now for the URI pattern, example: [LINK](https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fimage%2Fd4df12bb-bc94-34b1-ac46-0c8e9222c895&sid=683)

Updated the URI policy

**Comment by rtroncy** [comment]
Can this issue be closed?

**Comment by tschleider** [comment]
From my side, yes.
