### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by DominicClermont** [silknow/converter#38]
Some of the image links from the URL field in the knowledge graph seem to be broken. All URLs are referring to the silknow server (http://silknow.org/silknow/media/...). I'm appending a .txt file with all image links that seem to be broken. 
[missing_links.txt](https://github.com/silknow/converter/files/3968629/missing_links.txt)

Every line in the file lists one URL as well as the identifier we are using for uniquely naming the downloaded image files. This identifier also shows the URI of the corresponding record, maybe this can help identifying the problem.

**Comment by rtroncy** [comment]
We seem to be not done even though we have closed the famous issue #13! Looking at the txt file, I see that some mistakes clearly come from the converter code in the way it builds the deeplink pointing to the image hosted on the silknow media server, while some other mistakes may come from @javier-sevilla.

@pasqLisena Can you have a look at the converter code and report on the errors you can see?

**Comment by javier-sevilla** [comment]
Hello @pasqLisena

Asap you send the file we work to solve the broken links.

**Comment by pasqLisena** [comment]
## MFA

Most of the external image links are of the type:

`https://mfas3.s3.amazonaws.com/styles/fair_use/s3/objects/<IDENTIFIER>.jpg?itok=<ITOK>`

The ITOK is an access token generated by Drupal -- [read more](https://ma.ttias.be/drupals-itok-parameters-explained-varnish-workaround-different-backends/).

Anyway, this ITOK part is not anymore on the website, in which the image URI has changed to:

`https://collections.mfa.org/internal/media/dispatcher/<IDENTIFIER>/preview`

Example:
* Record https://collections.mfa.org/objects/571191
** Image https://collections.mfa.org/internal/media/dispatcher/1506328/preview
** Silknow Record http://data.silknow.org/object/63febc7a-3271-3335-9d5a-9dc33ead5c99
** Silknow Image (Broken) https://mfas3.s3.amazonaws.com/styles/fair_use/s3/objects/SC361144.jpg?itok=2TbUpxh0
* Record https://collections.mfa.org/objects/45922
** Image https://collections.mfa.org/internal/media/dispatcher/708736/preview
** Silknow Record http://data.silknow.org/object/4b7f345b-2d12-3be8-a620-e8fd40c84111
** Silknow Image (Working) https://mfas3.s3.amazonaws.com/objects/C11011.jpg

From what I see, when the EXTERNAL uri image is broken, also the INTERNAL one is. In the same way, they are working only together.

Anyway, this is a problem that should be fixed running the crawler again, because 2 months ago there has been an [update](https://github.com/silknow/crawler/commit/a5c083d61de054dc3bb7083e7300a18d78b5895c) implementing the new logic for images. However, I am not able to run the crawler now because of  https://github.com/silknow/crawler/issues/10 , and the files on [owncloud](https://silknow.uv.es/owncloud/index.php/apps/files/?dir=/Data/mfa-boston/records&fileid=348563) are from 9 months ago (and I imagine that they are the one that we are converting so far).

So, once the crawler is fixed, we need to re-crawl files, re-convert them and upload the images with the new naming convention.

## CERES

The crawler assigns to images a filename (saved in the `localFilename` property) that is correctly read and used in the converter:
https://github.com/silknow/converter/blob/85c6c2cc9809896cffd2e0641f802691b63bb169/src/main/java/org/silknow/converter/entities/Image.java#L48

Even files like `CE20982!1_MNAD_5.jpg` are correct

## MET 

Records exist with no image -- [example](https://www.metmuseum.org/art/collection/search/339800)

These are wrongly represented by the crawler as  `https://images.metmuseum.org/CRDImages/` (being the pattern `https://images.metmuseum.org/CRDImages/<IDENTIFIER>`.
Fix for this in the crawler: https://github.com/silknow/crawler/commit/0aa2122d17d42cd32921058c08f63955cabea62e

The same uris were converted in internal (ttl) as `http://silknow.org/silknow/media/met-museum/` (being the pattern `http://silknow.org/silknow/media/met-museum/<IDENTIFIER>`. 
Fix for this in the converter: f319c30

**Comment by rtroncy** [comment]
Excellent work @pasqLisena! My summary of your investigation:
- MFA: we need to solve issue https://github.com/silknow/crawler/issues/10, the re-crawl (records + images), re-convert in RDF and put the new images on the media server. This will not be done before next year.
- CERES: this is all good on our side, so this is for @javier-sevilla to check why those files are not served. @javier-sevilla Can you please check the 205 links starting by `cer__` in https://github.com/silknow/converter/files/3968629/missing_links.txt and make sure those images are served from the media server?
- MET: thanks for the fixes. We also need to solve the issue https://github.com/silknow/crawler/issues/10 before re-crawling and re-converting in RDF

**Comment by pasqLisena** [comment]
> MET: thanks for the fixes. We also need to solve the issue silknow/crawler#10 before re-crawling and re-converting in RDF

We can also do a DELETE query on the DB in order to remove from now all the wrong links.

And take into account that for MET there are still good links that are not found http://silknow.org/silknow/media/met-museum/19724a.jpg

**Comment by javier-sevilla** [comment]
We'll do it, today is a busy day, but we try will be finished tomorrow maximum.

**Comment by rtroncy** [comment]
> > MET: thanks for the fixes. We also need to solve the issue [silknow/crawler#10](https://github.com/silknow/crawler/issues/10) before re-crawling and re-converting in RDF
> 
> We can also do a DELETE query on the DB in order to remove from now all the wrong links.

Correct! A DELETE patch could indeed work. We would need to be cautious though, since those are cases where the museum record has **no** illustrating images. If I'm taking your example of the object identified by `<http://data.silknow.org/object/6dae100b-21f5-316f-b435-fa6134393145>`, this would mean not only deleting the object `<http://data.silknow.org/object/6dae100b-21f5-316f-b435-fa6134393145/image/1>` but also the statement 
```
  <http://data.silknow.org/object/6dae100b-21f5-316f-b435-fa6134393145>
      ecrm:P138_has_representation
          <http://data.silknow.org/object/6dae100b-21f5-316f-b435-fa6134393145/image/1>
```

Further, we should also modify the dump, otherwise, we would need to re-apply the same patch the next time we loaded the resources.
This is all do-able, but do you really want to do this?

> And take into account that for MET there are still good links that are not found http://silknow.org/silknow/media/met-museum/19724a.jpg

Correct! This is for @javier-sevilla !

**Comment by pasqLisena** [comment]
> Further, we should also modify the dump, otherwise, we would need to re-apply the same patch the next time we loaded the resources.

Well, next time that we load the dump, there will be a new dump :) So I would not do it on the dump

> This is all do-able, but do you really want to do this?

I would do the DELETE query, if this help @DominicClermont in his work

**Comment by pasqLisena** [comment]
## GARIN

There were 2 problems here (both fixed in 0d3e897).

#### Badly parsed uppercase `.JPG` (that was leading to `.JPG.jpg`

Before: http://silknow.org/silknow/media/garin/GP01043_ANV.JPG.jpg
Now: http://silknow.org/silknow/media/garin/GP01043_ANV.jpg

However, this link is still not working and neither is
http://silknow.org/silknow/media/garin/GP01043_ANV.JPG

#### Files with 2 whitespaces

Example: GP00084 -> http://data.silknow.org/object/0b4e77fa-4f24-31ec-8af0-1d6734b7b654

The converter search in the image folder all the files that start with `GP00084`, finding:
- `GP00084 REV.jpg`
- `GP00084  ANV.jpg`

For producing the locator, it replaces all the whitespaces ` ` with an underscore `_`, generating:
- http://silknow.org/silknow/media/garin/GP00084_REV.jpg (no problem here 🆗 )
- http://silknow.org/silknow/media/garin/GP00084__ANV.jpg  (not working 🔴 )

Given that http://silknow.org/silknow/media/garin/GP00084_ANV.jpg (only 1 underscore 🆗) is working, I added the rule of replacing double whitespaces with a single underscore (`  ` => `_`)

(all similar examples in @DominicClermont 's txt were behaving in the same way)

**Comment by pasqLisena** [comment]
## Summary

Summary of my investigation

  | probably problem about img copy | need new run of crawler | need new run of converter | need new copy of imgs after crawling/conversion
-- | -- | -- | -- | --
ceres | x |   |   |  
garin | x  |   | x |  
imatex | x |   |   |  
met | x | x | x |  
mfa-boston |   | x | x | x
vam | x |   |   |  

In particular for MET, the problem I described in [my previous comment](https://github.com/silknow/converter/issues/38#issuecomment-566647802) has been fixed on crawling/conversion side, but there are still some images missing. Examples:
- http://silknow.org/silknow/media/met-museum/Gozzoli%20altarpiece.jpg
- http://silknow.org/silknow/media/met-museum/19724a.jpg
- http://silknow.org/silknow/media/met-museum/6836.jpg

**Comment by rtroncy** [comment]
> I would do the DELETE query, if this help @DominicClermont in his work

OK, please, go ahead.

**Comment by rtroncy** [comment]
> ## GARIN
> There were 2 problems here (both fixed in [0d3e897](https://github.com/silknow/converter/commit/0d3e8971ce0dc1dc9569fe6191575863f4f409cf)).

Thanks for those fixes. I confirm that we agreed to lower case the extension, so `.jpg` and not `.JPG`.

**Comment by rtroncy** [comment]
@javier-sevilla Can you please read carefully this entire github thread and let us know precisely what you will do? This is relatively urgent for @DominicClermont !

**Comment by javier-sevilla** [comment]
Sure, we try to do it during this morning.

**Comment by pasqLisena** [comment]
>> I would do the DELETE query, if this help @DominicClermont in his work

> OK, please, go ahead.

Done. Query here

```sparql
WITH <http://data.silknow.org/met>
DELETE { ?parent ecrm:P129_is_about ?img . ?parent2  ecrm:P138i_has_representation ?img . ?img ?p ?q} 
WHERE {
  ?img a ecrm:E38_Image;
     ?p ?q;
     schema:contentUrl <https://images.metmuseum.org/CRDImages/> .
  ?parent ecrm:P129_is_about ?img .
  ?parent2  ecrm:P138i_has_representation ?img.
}
```

**Comment by javier-sevilla** [comment]
Hello @DominicClermont

I think that there is problem, I'm not sure if you are using a updated data, or something wrongs happens.

We were starting to check the files you have sent and:

- vam files, it is right that files are not in the media server, but those files are not in the tar.gz file provided by EURECOM, which content is copied in the media server. Well we check the first files of the list, but I think is the same problem with the rest of the files. For instance, the first 
(vam__f36753d1-08f9-38b0-ae10-dfc749b437de__817,http://silknow.org/silknow/media/vam/2017KB4259.jpg)
It is not in the media server and it is not in the tar.gz file

- mfa files, there is a mistake in the name of the file. in the list appear:

mfa__c0f2fd2a-4988-39dc-be52-2a30bbc03599__1903,http://silknow.org/silknow/media/mfa-boston/SC1077.jpg?itok=qM4nvtfN

But in the media server and also in the tar.gz providedn by EURECOM appears with "!" instead of "?", it is normal because the ? is understood by a parameter in url for the website.

With imatex is the same
imatex__35f0f1d6-fa7d-3963-80fd-9558a5a6165f__3931,http://silknow.org/silknow/media/imatex/0000046816.jpg

This files is not in the media server but also it is not in the tar.gz provided by EURECOM.
I think that there is a kind of misunderstanding, please check what happen in order to find  the best.

**Comment by rtroncy** [comment]
@javier-sevilla I have updated your github message (once more) for better readibility @DominicClermont is just taking links out of the knowledge graph and dumps from owncloud. I will further investigate, but, once more @javier-sevilla can you tell us precisely where are the latest version of everything? I remind you that owncloud is still a mess, despite our numerous messages. Let's start by cleaning this! In short, delete what needs to be deleted and tell us precisely where are the latest dump version of ALL museum crawls and what is being served from the media server! Give us statistics as the count of images served for each museum source so we can cross-check! Thanks!

**Comment by javier-sevilla** [comment]
I'm going to delete the temporal folder and create a folder for dumping crawled data. Like we talked in Hanover meeting, all the files in that folder must follow a format that shows the date of the file.

This format could be: `yyyymmdd.museumName.type.extension`

For instance, if the mfa museum is crawled again today, you must upload the files:

- 20191220.mfa.media.tar.gz
- 20191220.mfa.records.tar.gz

All these files will be saved in the [Data](https://silknow.uv.es/owncloud/index.php/apps/files/?dir=/Data&fileid=626898) folder on owncloud.

All the previous folders data content are deleted, but I backup, if you need something, please ask me for it.

In addition, I am talking with our admin in order to give  you an user to get direct access to the server. I think it could be very quickly. Like you know we are very busy to upload the files immediately in the server and this fact generates delays in the Project. I hope these actions help to reduce the delays updating the media server.

**Comment by rtroncy** [comment]
@javier-sevilla I have edited on github.com your previous email since it was containing mistakes! Please check. The markdown formatting is also not applied since you did a reply by email. Please, do NOT do this. Markdown formatting is not supported when doing email reply.

**Comment by tschleider** [comment]
@javier-sevilla 
I just checked the owncloud and I cannot find any dumps anymore? Also the version of Garin that you yourself modified seems to be gone? 

If you have a backup, could you restore it? We said please delete old files in the /Data/ folder but COPY the dumps from the temporary folder (which has also been deleted).

**Comment by javier-sevilla** [comment]
Yes I'll restore it in a while.

**Comment by tschleider** [comment]
@DominicClermont : we re-converted and uploaded the datasets for MET and GARIN, could you check if it's better now? 

For the rest there is still more work / testing to be done, I will maybe also create a small script to verify the image URIs myself

**Comment by tschleider** [comment]
Thanks to @pasqLisena  and @ehrhart  we could make quite some progress on this: 
We reduced the amount of dead links from over 1600 to less than 600. 
[silknow-urls-missing.txt](https://github.com/silknow/converter/files/4091651/silknow-urls-missing.txt)

For the remaining ones: 

There is a big group of VAM links that are broken due to VAM, which means the links are also dead on their website and that's how we crawl them. We decided to add another field in the image array with the crawler that confirms if image links actually work or not. With this we can filter dead links out either through the conversion or by querying. This concerns already more than half of the remaining dead links. Example on their website of an object we crawled (including the only working image with is perfectly integrated): [O73839](http://collections.vam.ac.uk/item/O73839/brocaded-velvet-unknown/) 

Some files are indeed not on the mediaserver, even though they should, we look further into this.

Some remaining files have a very small amount of dead links, we will look into them last. 
I tried to extend / update @pasqLisena  table with the new findings. 


  | probably problem about img copy | need new run of crawler | need new run of converter | need new copy of imgs after crawling/conversion |  remaining links
-- | -- | -- | -- | -- | -- 
ceres |x |   |   |  |203
garin |? |   |  |  |22
imatex |x |   |   |  |23
met |? |  |  |  |8
mfa-boston |? |  |  | |4 
vam |  |?  |   |  |323

**Comment by tschleider** [comment]
Newest update: 381 dead links remaining. 
[silknow-urls-missing.txt](https://github.com/silknow/converter/files/4109201/silknow-urls-missing.txt)

@DominicClermont : That's counting with our methods. Feel free to check if the situation is improving or if you're having a different experience!

**Comment by rtroncy** [comment]
@tschleider Great. Can you provide explanations for the various cases that remain? I can understand that a original link pointing to a media from the museum web site is now a 404, but I cannot understand why a local link could be broken. Also, can you provide an explanation of how you resolve what used to be dead links?

**Comment by tschleider** [comment]
Added the "schema:error" property to every E38_Image class with a dead external link ( based on a new functionality of the Crawler thanks to @ehrhart ) . The generation of an internal link will be prevented as well. This should remove most of the remaining dead internal links. 

@rtroncy : It's indeed a broken original link as far as we could see. We did not have a mechanism to detect this and prevent the generation of wrong local links to nothing. Now I will reconvert over the weekend with the newest dumps and we should have some new results on Monday.

**Comment by rtroncy** [comment]
The https://schema.org/error property is certainly not a wise choice, as it should be applied on Action! I still don't really understand the issue. If the crawler has, at least once, got the images, then we have a local copy and we cannot have a dead link. Having external dead links is not a problem.

**Comment by tschleider** [comment]
What would be wiser? I do not know which property would be better, as I indeed want to signalise a failed action: the attempted image download with a dead link by the crawler.

Having external dead links is not a problem? I thought maybe it would be great to mark the dead links somehow, that's why I added it. If it's not I can just remove it. Internal links are not longer generated for dead links, so after the next reconversion the following days the issue should be completely fixed, unless there is another problem with some of the remaining links.

**Comment by rtroncy** [comment]
Knowing whether an external link is dead at a particular moment in time is a dead cause. It would require to do GET or HEAD check regularly for little benefit. I would simply save in the knowledge graph the external link as it is at the time of crawling and, of course, materialize the local copy link. This one will always work.

Therefore, please check that ALL records have illustrating images that are get-able via local links. Then, this issue can be closed.

**Comment by DominicClermont** [comment]
@tschleider I have repeated our procedure of downloading the images. I started with getting the latest list of links using the query at api/queries/wp4/imageURLs.sparql. The first thing I noted was that this list now (28.01.) has around 4.000 fewer records than when this thread started.

Concerning the links, with our counting method we find 6.452 records with dead links: 
[missing_links_new.txt](https://github.com/silknow/converter/files/4147164/missing_links_new.txt)

Most of them are from VAM (2657), MET (2219) and Imatex (1062).

**Comment by tschleider** [comment]
I am in the middle of reconversion and reupload right now actually,
especially for these datasets you mentioned.

It should all be ready around Wednesday.

**Comment by rtroncy** [comment]
@tschleider I thought this was a solved issue. Are you sure, as well, that all images that have been crawled, have been copied and are locally served from http://silknow.org/silknow/media/xxx?

@DominicClermont should not have to check since you can do it yourself with a simple [HEAD request](https://riptutorial.com/javascript/example/15188/check-if-a-file-exists-via-a-head-request) for each file

**Comment by tschleider** [comment]
@rtroncy all different cases that we have found are solved from a coding and media server perspective, both in the crawler and converter, but we needed quite some re-crawls and re-conversions on the way and it's not done today. I will confirm and close once we cannot find any broken links anymore. I can give an exact update tomorrow.

Of course we can check ourselves, maybe I formulated it not clearly enough. I just meant for @DominicClermont to not check before we are done with the hopefully final re-uploads and it would be good just to have a confirmation that they do not find any dead links anymore either.

**Comment by tschleider** [comment]
Status: 
Right now we have 17318 broken links due to the fact that we completely re-uploaded re-crawled all images after several bugfixes in both the crawler and the converter the last weeks.

The good news: There are 0 dead links except for Imatex, RISD and MFA right now, which means nothing unexpected anymore. We just uploaded the new image format too early without waiting for the full conversions. These are the datasets where we had some late re-crawls/re-conversions and it should be done tomorrow (for Imatex) and maybe even today for the other 2.

**Comment by tschleider** [comment]
Now there are finally 0 dead links, as far as we can see. 

@DominicClermont : We realised that (at least) MFA changed their classification of what is a "textile" (which is the only category we crawled - instead they put some of these objects into more fine-grained categories like "costumes" etc. ), which means several thousand less records than in December, so some of your observations of less records might still be true, but this should not be a problem for WP4. 

@rtroncy : I guess it's another topic and I would like to close this here, but we probably need to decide if we extend the categories of the MFA crawl.

**Comment by rtroncy** [comment]
> @rtroncy : I guess it's another topic and I would like to close this here, but we probably need to decide if we extend the categories of the MFA crawl.

This is indeed another topic. I suggest you write an email to the list and in particular to Jorge to ask for his opinion whether the crawl should be enlarged or not giving him examples of additional objects that could be retrieved if we decide so.

I'm very happy to close this issue now.
