### ISSUE TITLE
Interpreting fuzzy location and clarifying if the location is the production place or something else

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#41]
This is a follow up of issue #19.

In some occasion, a place name may be preceded by a modal operator (such as 'maybe'). This first prevents an effective interlinking with Geonames but more importantly, it should be captured in the model.

Further, we always interpret the mention of a location as the production place of the object. This interpretation needs to be assessed by domain experts during an evaluation.

@tschleider Please, provide examples of fuzzy location mentions, when relevant, for each museum

**Comment by rtroncy** [comment]
Assigning it to @pasqLisena as there are similarities with #66

**Comment by pasqLisena** [comment]
Things have been evolved since January.

Currently, only [3680 places](https://data.silknow.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+count%28%3Floc%29+%23+%3Fg+%3Flabel+count%28distinct+%3Fprd%29%0D%0AWHERE+%7B%0D%0A+++++++GRAPH+%3Fg+%7B+%3Fprd+ecrm%3AP108_has_produced+%3Fobj+%7D%0D%0A+++++++%3Fprd+ecrm%3AP8_took_place_on_or_within+%3Floc+.%0D%0A+++++++%3Floc+rdfs%3Alabel+%3Flabel%0D%0A+++++++FILTER+NOT+EXISTS+%7B+%3Floc+rdf%3Atype+geonames%3AFeature+%7D%0D%0A%7D+ORDER+BY+desc%28count%28distinct+%3Fprd%29%29&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+) are not interlinked with Geonames, while [194670](https://data.silknow.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+count%28%3Floc%29+%23+%3Fg+%3Flabel+count%28distinct+%3Fprd%29%0D%0AWHERE+%7B%0D%0A+++++++GRAPH+%3Fg+%7B+%3Fprd+ecrm%3AP108_has_produced+%3Fobj+%7D%0D%0A+++++++%3Fprd+ecrm%3AP8_took_place_on_or_within+%3Floc+.%0D%0A+++++++%23+%3Floc+rdfs%3Alabel+%3Flabel+.%0D%0A+++++++%23+FILTER+NOT+EXISTS+%7B+%0D%0A+++++++%3Floc+a+geonames%3AFeature+%0D%0A+++++++%23+%7D%0D%0A%7D+ORDER+BY+desc%28count%28distinct+%3Fprd%29%29&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+_) are interlinked.

Looking at the [not linked ones](https://data.silknow.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+%3Fg+%3Flabel+count%28distinct+%3Fprd%29%0D%0AWHERE+%7B%0D%0A+++++++GRAPH+%3Fg+%7B+%3Fprd+ecrm%3AP108_has_produced+%3Fobj+%7D%0D%0A+++++++%3Fprd+ecrm%3AP8_took_place_on_or_within+%3Floc+.%0D%0A+++++++%3Floc+rdfs%3Alabel+%3Flabel+.%0D%0A+++++++FILTER+NOT+EXISTS+%7B+%3Floc+a+geonames%3AFeature+%7D%0D%0A%7D+ORDER+BY+desc%28count%28distinct+%3Fprd%29%29&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+):
- the wide majority (weighted on the count of involved objects) are places not available (and hard for us to insert) in geonames, like Far East or Al-Andalus. These are already represented as a single object (using the label as seed for UUID). We can create a unique object for merging "Extrem Orient", "Far East" and "Extremo Oriente", just for harmonising this particular case
- There are then alternative places in the text, like "French or English", "Italian, Spanish or French" or even "Italian or Oriental" (so neither a continental reduction works here). I don't know what can we do here, we really need a property different from `ecrm:P8_took_place_on_or_within`
- There are Italian labels which may work by removing "Arte" or "Ambito", like in "Arte di Zoagli" or "Ambito veneziano"
- The cases patronymic + city (e.g. "French (Lyon)" or "Italian (Lucca)") should also be feasible
- We should remove the `(Made)` part of the label
- We should remove `for export` and similia

Then of course there will be always a bit of noise, but this is unavoidable. (e.g. "No se descarta la posibilidad de estar fabricado en Valencia con una cromolitografía importada.")

We are removing for interlinking all "possibly", "probably", etc.

We are removing for interlinking all these texts:
https://github.com/silknow/converter/blob/2df380e62ebad20840c9f715c2600a6d32fa5787/src/main/java/org/silknow/converter/entities/Place.java#L37-L39
What about "London (Printed)" or "London (upholstered)" or "Menton (sold)"? 
What should we do for the rest?
I propose to collect all possible "actions" (so made, print, manufacture, sew, design, publish, ...) and create an exhaustive list (with numbers) for the historians.

**Comment by rtroncy** [comment]
Excellent study!

Yes, do create a list of possible "actions" since this may trigger an improved modeling of the data. I'm inquiry the experts as well.

Regarding the removal of uncertainty qualifiers such as 'possibly', 'probably', this is good for improving interlinking. However, I wonder whether we should not capture this information in the model as well, which would mean use a different property than `ecrm:P8_took_place_on_or_within` or at least add the uncertainty somewhere. Again, I'm inquiry the experts about this issue.

**Comment by pasqLisena** [comment]
So, I largely improved the coverage of the parsing (following what I wrote in the comment above).

In the parsing, we are ignoring the part about selling ("for export", "for American market") and usage ("used in America", "worn in America"). I don't know if this should be represented elsewhere,  but for sure this part is not relevant for the Production.

List of possible activities, present between brackets (e.g. in `Spain (designed)`).
- embroidering, embroidered, embroidery
- used
- made
- published
- designed, designed and made, designed (process)
- printed, printing, block printing
- collected
- sewing
- worn
- manufactured
- weaving, hand weaving, tapestry weaving
- woven
- quilted
- painting, painted
- retailed
- joinery
- sold
- upholstered
- altered
-  tambouring
- drawn
- purchased

For the moment, we are ignoring these for having as more links as possible.

This issue can be eventually closed (@rtroncy)

EDIT: these activities are also present in the times! E.g. `1720s (weaving), 1760s (sewing), 1920 - 1960 (altered)`. I am updating the list

**Comment by rtroncy** [comment]
I would keep it open until we get a resolution from [this thread](https://lists.eurecom.fr/sympa/arc/silknow/2021-01/msg00036.html).

**Comment by rtroncy** [comment]
Closing due to https://lists.eurecom.fr/sympa/arc/silknow/2021-03/msg00113.html
