### ISSUE TITLE
Make sure that object Titles are properly converted

### ISSUE THREAD

**Issue by rtroncy** [silknow/converter#59]
A large number of museums do provide a title. However, we often do not find it in the KG which questions whether this has been properly implemented.

Reference document: https://docs.google.com/document/d/10Kht6Rv-_4iHshKOC_GR8rmKtcxtAX0ndw0XWxP8PcI/edit# (third column)

For each museum, I suggest that each object has a `rdfs:label` AND a `P102_has_title` with the same value when given by the museum.
Example: https://ada.silknow.org/en/object/df09a64e-e5a1-3315-86a5-59a3534d9594 does not seem to have a label while there is a _Denominacion principal_ field in the record, right?

I think we should  no longer add E17 type assignment for titles.

This issue can be closed once ALL museums have been checked.

**Comment by tschleider** [comment]
Fixed and checked.

To avoid future confusion, some of the mappings need to be updated. In most cases a field with the name "title" is either mapped as E17 (MFA, MET) only or only as P102_has_title, but in some cases (e.g. [CER](https://docs.google.com/document/d/1qecnBVqxtTQ5GC4LRITixGdiLFf4zB6824B882zUgbg/edit#heading=h.vy2q0pvq298w)) it is still mapped as both. / cc @mpuren.

Right now, I made however sure that the mapping of E17 or P102_has_title is according to the aforementioned reference document and there are no "double mappings" anymore.

**Comment by ehrhart** [comment]
Should we construct the label directly in the generated KB instead of dynamically generating it on ADA?

From a conversation with Raphaël, the construction rule for is as follow:

* The value of `P102_has_title`, if there is one.
* OR, the object category (JOKER) + ', ' + the production time span label + ', ' + the production place label

I think it would make sense to generate an `rdfs:label` based on these rules. This would also help visualising objects in the facet browser or during queries.

**Comment by rtroncy** [comment]
To progress on this action, we should:
- no longer use an instance of the `E17_Type_Assignment` class.

- systematically, provide values for the 2 properties `rdfs:label` and `P102_has_title` where the value is coming: a) EITHER from a source field (see mappings); b) OR is artificially generated/constructed using [these rules](https://github.com/silknow/converter/issues/59#issuecomment-742529058).

**Comment by tschleider** [comment]
@ehrhart  

Just to make sure. With "production time span label" you mean the value from the time-span field? (Same for production place)

**Comment by ehrhart** [comment]
@tschleider I believe it would be the `rdfs:label` of the `P4_has_time-span` for production time, and the `rdfs:label` of `P8_took_place_on_or_within` for production place.

**Comment by tschleider** [comment]
I implemented this mechanism, see e.g.: 

https://data.silknow.org/describe/?url=http%3A%2F%2Fdata.silknow.org%2Fobject%2F280b1801-a9de-317d-b0c5-a5e275122b1a&sid=303 

In general it follows the rule outlined by @ehrhart , but there are three exceptions:

- MAD has a combined field for time and place (which is normally not converted, yet, see #5 ) so instead of "time + place" I just add the value(s) of the "Création:" field.

- UNIPA / Sicily: The new records do not have a mapping for a JOKER / type of object value and location, therefore I cannot use it. The field mentioned in the new Google Doc (joker / batman) exists only in the old one.

- MTMAD: Fortunately it looks like MTMAD has a proper title field (one of the few fields that it has at all), but it does not have proper type of object, date or location labels (see #9) , so I cannot use them for the generation of a title (maybe they all have an explicit title, I didn't check).

**Comment by rtroncy** [comment]
@tschleider Hum, why is it displaying "(made)" twice in https://data.silknow.org/object/280b1801-a9de-317d-b0c5-a5e275122b1a?

The label of the time span is simply "1700-1800", see https://data.silknow.org/timespan/925e9303-3789-317b-9892-15f4832d40cb. The label of the geonames entity is also simply "China".

Between, do not forget to add a proper dereferencing rule for the URI https://data.silknow.org/timespan/xxx

For MTMAD, if there is a real title, you do not need to "construct" a title. Is it the case or not?

**Comment by tschleider** [comment]
Ok, so generating a title out of the fully processed time span and geonames name was not super trivial with our current converter architecture. After many tries of us,  @ehrhart came up with a great query ([LINK](https://github.com/silknow/knowledge-base/blob/master/patches/01-insert_objects_labels.rq)) that constructs an rdfs:label as discussed - in case the P102 title is missing - during the deployment. We integrated it into our normal upload / re-deployment workflow. 

Almost no code on the converter side was relevant for this in the end, but we think it's the better solution.

Results can be easily seen on ADASilk: e.g. https://ada.silknow.org/browse?type=object&page=1

**Comment by rtroncy** [comment]
Yes, this was a clever idea we used at the 3cixty KG construction time, with plenty of patches to clean up the KG during deployment time. Well done @ehrhart !

We said we would use both the `rdfs:label` AND the `P102_has_title` properties. The INSERT clause needs to be updated accordingly.

Next, the constructed title is never localized. Is it intended?

**Comment by ehrhart** [comment]
> We said we would use both the rdfs:label AND the P102_has_title properties. The INSERT clause needs to be updated accordingly.

The query has been updated to add P102_has_title.

> Next, the constructed title is never localized. Is it intended?

Question: how to determine the language of the label? 🙂 
None of the properties used (assignment label, time label, place label) seem to have the language tag.
We can always set it to english by default, if needed.

**Comment by rtroncy** [comment]
Let's keep it like this for now. We will see if there is a need for localization later.
